[package]
name = "jc3gi"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
glam = { workspace = true }
windows = { workspace = true }

[build-dependencies]
pyxis = { workspace = true }
